name: Build Executable with PyInstaller

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Run PyInstaller
        run: |
          pyinstaller --add-data "data:data" main.py

      - name: List contents of dist/ directory
        run: |
          echo "Listing contents of dist/ directory..."
          ls -l dist/
        
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/
